#!/usr/bin/env python3

import argparse
import os

from modules.pogi_commands import pogi_week_summaries
from modules.pogi_commands import pogi_show, pogi_week_summaries

CONF_NAME = "ogi.conf"
sysdir = os.path.dirname(os.path.realpath(__file__))


def parse_arguments():

    def default_func(args):
        print("Must specify tool (ogi <tool>)"
              "\nIf it is the first time you run Ogi, it is recommended to run the 'ogi setup' command to set up a "
              "config file and to initialize the SQLite database.\n")
        parser.print_help()
        exit(1)

    parser = argparse.ArgumentParser()
    parser.set_defaults(func=default_func)

    subparsers = parser.add_subparsers(help='Commands:')

    parse_show(subparsers)
    parse_week_summaries(subparsers)

    args = parser.parse_args()
    args.func(args)


def parse_show(subparsers_object):

    """Subparser for new command"""

    def ogi_show_func(args):
        pogi_show.main(args)

    subparser = subparsers_object.add_parser('show')
    subparser.set_defaults(func=ogi_show_func, which='show')

    subparser.add_argument('show_type', nargs='?', choices=['week', 'month'])

    # subparser.add_argument('object_type', choices=['show_week'])
    subparser.add_argument('--dry_run', action='store_true')
    subparser.add_argument('--do_not_show', action='store_true')

    subparser.add_argument('--open_new_window', action='store_true')


def parse_week_summaries(subparsers_object):

    """Print brief week summary"""

    def pogi_week_summaries_func(args):
        pogi_week_summaries.main(args)

    subparser = subparsers_object.add_parser('week_summaries')
    subparser.set_defaults(func=pogi_week_summaries_func)


if __name__ == "__main__":
    parse_arguments()
